dist: trusty
language: node_js
node_js:
  - "8"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
# cache:
#   yarn: true
install:
  - yarn install
script:
    - yarn update
    - yarn prettier