dist: trusty
language: node_js
node_js:
- '8'
env:
  global:
  - USERNAME="numb95"
  - EMAIL="amir@goodarzi.net"
  - REPONAME="awesome-persian-youtubers"
  - README="README.md"
  - GHREPOURL="github.com/${USERNAME}/${REPONAME}.git"
  - TRAVIS_SECURE_TOKEN_NAME="travis"
  - secure: MKJF3c5HkAgnJt171x2DgRuH14NCvnRyZIf09Uc9q5vsXRAsQWRXRmdXeLjU8mH/mjNd/japeAkC/uMuywr4TG6oaaA5R9TOg37dKpI48b1M6aXMATx2RyXa24wQxG19szKVknCSrUp8mvFj5ASkabLUQM0ubCWy1tTvaxjj9BtXYmPc9f5H6TISFsJ8rAhAkyTDo5PKAmFc2YFP+HRvULk7Mvf0e9dg+k5Xdx/1Y05UZeG6dXq9FBKlrONNwpPmdQ1V3Y00LyqabytyOyPIHhSs9AxynAwFABlcJAvmb9WotzIwj7oVn+KTqCGi2aqPgHMdavQwIK1dNTkFlg5og7TDbaMq+lCIWOPMIdxt+ouNlg6JPB5NQfviH3pwU/dTRm2GCDBY0BRKHb7tznu2svFjGRj5IzQIfxTcEC7zox++E7W9KcCPo3k0nXZ/Zad1iv1eVzH+5SQJnLA2MJL01Xxgetg7FAlQZ3evxxujoeXcncTfu2/RkPW3fK+3dM1/ILRFBssheqCEFs2q3bzm7tWXTp9idGZbJoKk8JiHKbIGGU3RXNRbuw6gjjAZEcamhpKbLOeMLtekL+fypt+jN2RgetjDhmt5QuzgA/l0ZA2N1uGxvgz6P705Ozb1dpPXAgoSKkJwfrlZYa2orkQV0hxG55XMrmKk+dMbOTvzoWg=
"--before_install":
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$PATH"
install:
- yarn install
script:
- yarn update
- yarn prettier
after_success:
- git clone git://${GHREPOURL}
- mv -f ${README} ${REPONAME}
- cd ${REPONAME}
- git remote update
- git fetch
- git config user.email ${EMAIL}
- git config user.name ${USERNAME}
- git add ${README}
- git commit -m "Travis push to repo"
- git push "https://${GH_TOKEN}@${GHREPOURL}" master
