dist: trusty
language: node_js
node_js:
- '8'
env:
  global:
  - secure: eeH6yeH7jdzcCbQQFFRXOZQiOisjZpBd9TIf7+NuXrxQQ9qbHKdLP2z5mY57a1u7ZSG5FhVd/+Q6+v14gN5Ho3pHo3jPL6kBKICWUkWzW8AII2SU94irD3l8KWzf3ajzRQ6zmRIUwlB4rGDslEPR0omtP8LKTuJczGNsN5Cy2f7aGwEa0T6CTH+PBFvp7Pv8Yzk4sCNs0lx15KdpO2Vfq8PWtj17Bxp0JBK21mUwxHYcg6PB4rSOIG5vuZgqnyrjSZeZ+xr6zfjf6gWexk+0t1L2WfZ6W9XvY/yCvjIUO5mxmfZ01AdaBRv41Od80iN8cx5KQgzvoIVir1AgpmROOIpFu8j/XhWPv5Br2sYwiyptYFkZTbvtKejBim9jRNBJptt/gX76P0jZIZ38bASizNHDzeamxtDS7E9cNw32GOC7ojyQJsA1N1HXmTrwdLPd+0iq6S5FK2m2bwKv9l6EToWRC9TDu5AdvuQHw2lzdarDvEnsfjrLv2rOSjK2D8Vur3bS4QNJYObdxaDw2nu6op3dnPCIor3M+7Mu3D7iyxT5fUh9nav+vbOwy5begCnSgcMz8wei7svYgOEQUvUrOv85shZjnZKhy7wcVGOXdFmn0g+FNDKNlLCiIHSPawa6lmOiXOWiHaZGUhT9aGIH8DtemSOxATo3A+BOoW+3NI4=
--before_install":
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$PATH"
install:
- yarn install
script:
- yarn update
- yarn prettier
after_success:
- git config --global user.email travis@travis-ci.org
- git config --global user.name "Travis CI"
- git checkout master
- git add README.md
- git commit -m "Travis push to repo. Ref: $TRAVIS_BUILD_NUMBER"
- git remote add origin-pages https://${GH_TOKEN}@github.com/numb95/awesome-persian-youtubers.git > /dev/null 2>&1
- git push --quiet --set-upstream origin master
